name: mbeerti
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0-179.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.18
  get_storage: ^2.1.1
  flutter_cube: ^0.1.1
  model_viewer_plus: ^1.5.0
#  babylonjs_viewer: ^1.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: LOB
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf
          weight: 700
    - family: NTKR
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
    - family: GD
      fonts:
        - asset: assets/fonts/Gowun_Dodum/GowunDodum-Regular.ttf
          weight: 400
    - family: HH
      fonts:
        - asset: assets/fonts/Hahmlet/static/Hahmlet-Thin.ttf
          weight: 100
        - asset: assets/fonts/Hahmlet/static/Hahmlet-Regular.ttf
          weight: 400
        - asset: assets/fonts/Hahmlet/static/Hahmlet-Bold.ttf
          weight: 700


